version: '3.8'

services:
  asf:
    image: justarchi/archisteamfarm:latest
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./asf/config:/app/config
      - ./asf/plugins:/app/plugins

  dashboard:
    build: .
    restart: always
    ports:
      - "3000:3000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    depends_on:
      - asf
    volumes:
      - ./asf/config:/app/asf-config
    environment:
      - ASF_IPC_URL=http://asf:1242/Api/Command
      - ASF_PASSWORD=mein_sicheres_ipc_passwort
      - STEAM_MAIL_PASSWORD=dein_tatsächliches_imap_passwort
      - CSREP_API_KEY=dein_tatsächlicher_csrep_api_key
      - CSREP_KEY_ID=dein_tatsächlicher_csrep_key_id

